name: Java CI với Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Lấy source code
      uses: actions/checkout@v3

    - name: Thiết lập Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cài dependencies và build dự án
      run: ./mvnw clean install

    - name: Chạy test
      run: ./mvnw test
